#! /bin/sh
if [ ! -d /var/arcyd ]; then
    mkdir /var/arcyd
    cd /var/arcyd
    git config --global user.email ${ARCYD_EMAIL}
    git config --global user.name ${ARCYD_NAME}
    arcyd init --arcyd-email ${ARCYD_EMAIL} || exit 1
fi
cd /var/arcyd
arcyd start --foreground
