#! /bin/sh
set -x
REPO_URL=$1
if [ ! -d /var/arcyd ]; then
    cd /var
    git clone $REPO_URL arcyd
    git config --global user.email ${ARCYD_EMAIL}
    git config --global user.name ${ARCYD_NAME}
fi
cd /var/arcyd
arcyd start --foreground
