#! /bin/sh
set -x
mkdir -p /data/git
cd /data/git
echo $@
for dir in $@; do
    git init --bare $dir
done
git daemon --verbose --reuseaddr --export-all --base-path=/data/git --enable=receive-pack /data/git
while sleep 1; do true; done
