#! /usr/bin/env bash

set -euo pipefail
set -x

docker run -d --name git --hostname git gitdaemon arcyd-config repo1 repo2
docker run -d --name arcyd-bootstrap arcyd-bootstrap
sleep 1

GIT_IP=$(docker exec git getent hosts git | awk '{print $1}')

cleanup() {
    # docker kill git
    # docker rm git
    docker kill arcyd-bootstrap
    docker rm arcyd-bootstrap
}
trap cleanup 0

run () {
    local COMMAND="cd /data/arcyd; "$@
    docker exec arcyd-bootstrap /bin/sh -c "$COMMAND"
}

setuprepo() {
    local REPO=$1
    local PREV_DIR=$(pwd)
    local TEMP_DIR=$(mktemp -d)
    cd "$TEMP_DIR"
    git clone git://$GIT_IP/$REPO
    cd $REPO
    touch README
    git add README
    git commit -m 'Initial commit'
    git push origin master
    cd "$PREV_DIR"
    rm -rf "$TEMP_DIR"
}

setuprepo repo1
setuprepo repo2

run git config --global user.name Arcyd
run git config --global user.email arcyd@localhost.invalid
run git clone git://git/arcyd-config .
run arcyd init --arcyd-email arcyd@host.test --sleep-secs 3
run arcyd add-repohost --name gitdaemon --repo-url-format 'git://git/{}'
run arcyd add-phabricator \
    --name phab-web \
    --instance-uri http://phab-web/api/ \
    --admin-emails 'local-phab-admin@localhost' \
    --arcyd-user phab \
    --arcyd-cert \
xnh5tpatpfh4pff4tpnvdv74mh74zkmsualo4l6mx7bb262zqr55vcachxgz7ru3lrvafgzqu\
zl3geyjxw426ujcyqdi2t4ktiv7gmrtlnc3hsy2eqsmhvgifn2vah2uidj6u6hhhxo2j3y2w6lcseh\
s2le4msd5xsn4f333udwvj6aowokq5l2llvfsl3efcucraawtvzw462q2sxmryg5y5rpicdk3lyr3u\
vot7fxrotwpi3ty2b2sa2kvlpf
run arcyd add-repo phab-web gitdaemon repo1
run arcyd add-repo phab-web gitdaemon repo2
run git push origin master
# -----------------------------------------------------------------------------
# Copyright (C) 2015 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------ END-OF-FILE ----------------------------------
