#!/usr/bin/env python3
# encoding: utf-8

import os
import sys

# Prevent nasty runtime surprises by enforcing version 3.x as early as
# possible.
#
# The version check itself will not work prior to Python version 2.0,
# that's when sys.version_info was introduced.
#
if sys.version_info[0] != 3:
    sys.stderr.write("You need python 3+ to run this script\n")
    exit(1)

# append our module dirs to sys.path, which is the list of paths to search
# for modules this is so we can import our libraries directly
# N.B. this magic is only really passable up-front in the entrypoint module
PARENT_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.append(os.path.join(PARENT_DIR, "py", "lor"))
sys.path.append(os.path.join(PARENT_DIR, "py", "phl"))

import lorcmd_linterate

if __name__ == "__main__":
    sys.exit(lorcmd_linterate.main())

# -----------------------------------------------------------------------------
# Copyright (C) 2013-2014 Bloomberg Finance L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------ END-OF-FILE ----------------------------------
